sudo: required
services:
  - docker

before_install:
  - docker build -t vijay/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true vijay/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-413915511261"
  bucket_path: "docker"
  on:
   branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
